-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (1, 'https://boston.com', 'http://tinypic.com/', 'fave fruit');
-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (1, 'https://dyndns.org', 'https://unc.edu', 'mood');
-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (2, 'http://nhs.uk', 'http://howstuffworks.com', 'fave veggie');
-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (2, 'http://homestead.com', 'https://51.la/nam/dui', 'fave creature');
-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (2,'http://163.com', 'https://stanford.edu', 'fave person');
-- insert into POLLS (user_id, sub_link, admin_link, name_required) values (3,'http://163.com', 'https://stanford.edu', 'poll_e');
