-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('bob', 1, 1, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('bob', 2, 2, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('bob', 3, 3, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 1, 1, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 3, 2, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 2, 3, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 3, 1, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 1, 2, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 2, 3, 1);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('mary', 1, 4, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('mary', 2, 5, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('mary', 3, 6, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('mary', 4, 7, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 1, 4, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 2, 5, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 3, 6, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Devan', 4, 7, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 1, 4, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 2, 5, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 3, 6, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Hughie', 4, 7, 2);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Almire', 4, 8, 3);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Almire', 4, 9, 5);
-- insert into SUBMISSIONS (voter_name, rank, option_id, poll_id) values ('Almire', 4, 10, 5);


